{% set name = "otumat" %}
{% set version = "0.3.1" %}

# test message1
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 52aca063d8b451a258720f3ead085efa34496d818a4c0d294eecda8040d5966c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - cryptography
    - flask
    - appdirs
    - watchdog
  run:
    - python >={{ python_min }}
    - cryptography
    - flask
    - appdirs
    - watchdog
test:
  imports:
    - otumat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/datajoint/otumat
  summary: A suite of maintainer tools and utilities for pip packages.
  description: |
    Otumat (pronounced "Automate") is a suite of maintainer tools and utilities for pip packages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guzman-raphael
